from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox, QApplication


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setMaximumSize(QtCore.QSize(300, 400))
        MainWindow.setBaseSize(QtCore.QSize(300, 400))
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label_ProgramName = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_ProgramName.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_ProgramName.setFont(font)
        self.label_ProgramName.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.label_ProgramName.setObjectName("label_ProgramName")
        self.label_Argument1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Argument1.setGeometry(QtCore.QRect(10, 55, 280, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_Argument1.setFont(font)
        self.label_Argument1.setStyleSheet("background-color: rgb(58, 156, 16);")
        self.label_Argument1.setObjectName("label_Argument1")
        self.label_AX = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_AX.setGeometry(QtCore.QRect(10, 100, 20, 25))
        font = QtGui.QFont()
        font.setFamily("C059 [UKWN]")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        self.label_AX.setFont(font)
        self.label_AX.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.label_AX.setObjectName("label_AX")
        self.spinBox_AX = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox_AX.setGeometry(QtCore.QRect(40, 100, 250, 25))
        self.spinBox_AX.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.spinBox_AX.setMinimum(-30000000)
        self.spinBox_AX.setMaximum(30000000)
        self.spinBox_AX.setObjectName("spinBox_AX")
        self.label_AY = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_AY.setGeometry(QtCore.QRect(10, 130, 20, 25))
        font = QtGui.QFont()
        font.setFamily("C059 [UKWN]")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.label_AY.setFont(font)
        self.label_AY.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.label_AY.setObjectName("label_AY")
        self.label_AZ = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_AZ.setGeometry(QtCore.QRect(10, 160, 20, 25))
        font = QtGui.QFont()
        font.setFamily("C059 [UKWN]")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        self.label_AZ.setFont(font)
        self.label_AZ.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.label_AZ.setObjectName("label_AZ")
        self.spinBox_AY = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox_AY.setGeometry(QtCore.QRect(40, 130, 250, 25))
        self.spinBox_AY.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.spinBox_AY.setMinimum(-64)
        self.spinBox_AY.setMaximum(319)
        self.spinBox_AY.setObjectName("spinBox_AY")
        self.spinBox_AZ = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox_AZ.setGeometry(QtCore.QRect(40, 160, 250, 25))
        self.spinBox_AZ.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.spinBox_AZ.setMinimum(-30000000)
        self.spinBox_AZ.setMaximum(30000000)
        self.spinBox_AZ.setObjectName("spinBox_AZ")
        self.label_Argument2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Argument2.setGeometry(QtCore.QRect(10, 190, 280, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_Argument2.setFont(font)
        self.label_Argument2.setStyleSheet("background-color: rgb(58, 156, 16);")
        self.label_Argument2.setObjectName("label_Argument2")
        self.label_BX = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_BX.setGeometry(QtCore.QRect(10, 230, 20, 25))
        font = QtGui.QFont()
        font.setFamily("C059 [UKWN]")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        self.label_BX.setFont(font)
        self.label_BX.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.label_BX.setObjectName("label_BX")
        self.label_BY = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_BY.setGeometry(QtCore.QRect(10, 260, 20, 25))
        font = QtGui.QFont()
        font.setFamily("C059 [UKWN]")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.label_BY.setFont(font)
        self.label_BY.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.label_BY.setObjectName("label_BY")
        self.label_BZ = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_BZ.setGeometry(QtCore.QRect(10, 290, 20, 25))
        font = QtGui.QFont()
        font.setFamily("C059 [UKWN]")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        self.label_BZ.setFont(font)
        self.label_BZ.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.label_BZ.setObjectName("label_BZ")
        self.spinBox_BX = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox_BX.setGeometry(QtCore.QRect(40, 230, 250, 25))
        self.spinBox_BX.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.spinBox_BX.setMinimum(-30000000)
        self.spinBox_BX.setMaximum(30000000)
        self.spinBox_BX.setObjectName("spinBox_BX")
        self.spinBox_BY = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox_BY.setGeometry(QtCore.QRect(40, 260, 250, 25))
        self.spinBox_BY.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.spinBox_BY.setMinimum(-64)
        self.spinBox_BY.setMaximum(319)
        self.spinBox_BY.setObjectName("spinBox_BY")
        self.spinBox_BZ = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox_BZ.setGeometry(QtCore.QRect(40, 290, 250, 25))
        self.spinBox_BZ.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.spinBox_BZ.setMinimum(-30000000)
        self.spinBox_BZ.setMaximum(30000000)
        self.spinBox_BZ.setObjectName("spinBox_BZ")
        self.pushButton_Calculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Calculate.setGeometry(QtCore.QRect(19, 324, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Cantarell Extra Bold")
        font.setPointSize(33)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_Calculate.setFont(font)
        self.pushButton_Calculate.setStyleSheet("color: rgb(0, 170, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.255435 rgba(0, 0, 255, 255), stop:0.521739 rgba(85, 0, 255, 255));")
        self.pushButton_Calculate.setObjectName("pushButton_Calculate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.close_shortcut = QtGui.QShortcut("Ctrl+Q", MainWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.close_shortcut.activated.connect(MainWindow.close)
        
        self.pushButton_Calculate.clicked.connect(self.calculate)

        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label_ProgramName.setText(_translate("MainWindow", "Калькулятор"))
        self.label_Argument1.setText(_translate("MainWindow", "Координты исполнителя"))
        self.label_AX.setText(_translate("MainWindow", "X"))
        self.label_AY.setText(_translate("MainWindow", "Y"))
        self.label_AZ.setText(_translate("MainWindow", "Z"))
        self.label_Argument2.setText(_translate("MainWindow", "Координты блока"))
        self.label_BX.setText(_translate("MainWindow", "X"))
        self.label_BY.setText(_translate("MainWindow", "Y"))
        self.label_BZ.setText(_translate("MainWindow", "Z"))
        self.pushButton_Calculate.setText(_translate("MainWindow", "Посчитать"))
        
        
    def calculate(self):
        AX=self.spinBox_AX.value()
        AY=self.spinBox_AY.value()
        AZ=self.spinBox_AZ.value()
        BX=self.spinBox_BX.value()
        BY=self.spinBox_BY.value()
        BZ=self.spinBox_BZ.value()
        
        CX = BX-AX
        CY = BY-AY
        CZ = BZ-AZ
        
        result = QMessageBox()
        result.setWindowTitle("Результат")
        result.setText(f"X= ~{CX}\nY= ~{CY}\nZ= ~{CZ}")
        result.setIcon(QMessageBox.Icon.Information)
        
        # copy_x_button = result.addButton("COPY X", QMessageBox\
        #     .ButtonRole.AcceptRole)
        # copy_y_button = result.addButton("COPY Y", QMessageBox\
        #     .ButtonRole.AcceptRole)
        # copy_z_button = result.addButton("COPY Z", QMessageBox\
        #     .ButtonRole.AcceptRole)
        
        # copy_x_button.clicked.connect(lambda: QApplication.clipboard()\
        #     .setText("~" + str(CX)))
        # copy_y_button.clicked.connect(lambda: QApplication.clipboard()\
        #     .setText("~" + str(CY)))
        # copy_z_button.clicked.connect(lambda: QApplication.clipboard()\
        #     .setText("~" + str(CZ)))
        
        
        result.setStandardButtons(QMessageBox.StandardButton.Close)
        
        result.exec()
        
        #print(f"X: {CX},Y: {CY}, Z: {CZ}")
       
        
        


def run_window():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
