name: Lint Codebase

on: [push, pull_request]

permissions:
  contents: write
  statuses: write
  checks: write

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Lint Codebase
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
