name: Lint Codebase

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Lint Codebase
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKENL: ${{ secrets.GITHUB_TOKEN  }}
